// Code generated by scripts/currency/codegen.go. DO NOT EDIT.
// Any changes made to this file will be overwritten the next time it is generated.

package money

const (
	XXX Currency = 0   // No Currency
	XTS Currency = 1   // Test Currency
	AED Currency = 2   // U.A.E. Dirham
	AFN Currency = 3   // Afghani
	ALL Currency = 4   // Lek
	AMD Currency = 5   // Armenian Dram
	ANG Currency = 6   // Netherlands Antillian Guilder
	AOA Currency = 7   // Kwanza
	ARS Currency = 8   // Argentine Peso
	AUD Currency = 9   // Australian Dollar
	AWG Currency = 10  // Aruban Guilder
	AZN Currency = 11  // Azerbaijan Manat
	BAM Currency = 12  // Convertible Mark
	BBD Currency = 13  // Barbados Dollar
	BDT Currency = 14  // Taka
	BGN Currency = 15  // Bulgarian Lev
	BHD Currency = 16  // Bahraini Dinar
	BIF Currency = 17  // Burundi Franc
	BMD Currency = 18  // Bermudian Dollar
	BND Currency = 19  // Brunei Dollar
	BOB Currency = 20  // Boliviano
	BRL Currency = 21  // Brazilian Real
	BSD Currency = 22  // Bahamian Dollar
	BTN Currency = 23  // Bhutan Ngultrum
	BWP Currency = 24  // Pula
	BYN Currency = 25  // Belarussian Ruble
	BZD Currency = 26  // Belize Dollar
	CAD Currency = 27  // Canadian Dollar
	CDF Currency = 28  // Franc Congolais
	CHF Currency = 29  // Swiss Franc
	CLP Currency = 30  // Chilean Peso
	CNY Currency = 31  // Yuan Renminbi
	COP Currency = 32  // Colombian Peso
	CRC Currency = 33  // Costa Rican Colon
	CUP Currency = 34  // Cuban Peso
	CVE Currency = 35  // Cape Verde Escudo
	CZK Currency = 36  // Czech Koruna
	DJF Currency = 37  // Djibouti Franc
	DKK Currency = 38  // Danish Krone
	DOP Currency = 39  // Dominican Peso
	DZD Currency = 40  // Algerian Dinar
	EGP Currency = 41  // Egyptian Pound
	ERN Currency = 42  // Eritean Nakfa
	ETB Currency = 43  // Ethiopian Birr
	EUR Currency = 44  // Euro
	FJD Currency = 45  // Fiji Dollar
	FKP Currency = 46  // Falkland Islands Pound
	GBP Currency = 47  // Pound Sterling
	GEL Currency = 48  // Lari
	GHS Currency = 49  // Cedi
	GIP Currency = 50  // Gibraltar Pound
	GMD Currency = 51  // Dalasi
	GNF Currency = 52  // Guinea Franc
	GTQ Currency = 53  // Quetzal
	GWP Currency = 54  // Guinea-Bissau Peso
	GYD Currency = 55  // Guyana Dollar
	HKD Currency = 56  // Hong Kong Dollar
	HNL Currency = 57  // Lempira
	HRK Currency = 58  // Croatian Kuna
	HTG Currency = 59  // Gourde
	HUF Currency = 60  // Forint
	IDR Currency = 61  // Rupiah
	ILS Currency = 62  // Israeli Shequel
	INR Currency = 63  // Indian Rupee
	IQD Currency = 64  // Iraqi Dinar
	IRR Currency = 65  // Iranian Rial
	ISK Currency = 66  // Iceland Krona
	JMD Currency = 67  // Jamaican Dollar
	JOD Currency = 68  // Jordanian Dinar
	JPY Currency = 69  // Yen
	KES Currency = 70  // Kenyan Shilling
	KGS Currency = 71  // Som
	KHR Currency = 72  // Riel
	KMF Currency = 73  // Comoro Franc
	KPW Currency = 74  // North Korean Won
	KRW Currency = 75  // Won
	KWD Currency = 76  // Kuwaiti Dinar
	KYD Currency = 77  // Cayman Islands Dollar
	KZT Currency = 78  // Tenge
	LAK Currency = 79  // Kip
	LBP Currency = 80  // Lebanese Pound
	LKR Currency = 81  // Sri Lanka Rupee
	LRD Currency = 82  // Liberian Dollar
	LSL Currency = 83  // Lesotho Loti
	LYD Currency = 84  // Libyan Dinar
	MAD Currency = 85  // Moroccan Dirham
	MDL Currency = 86  // Moldovan Leu
	MGA Currency = 87  // Malagasy Ariary
	MKD Currency = 88  // Denar
	MMK Currency = 89  // Kyat
	MNT Currency = 90  // Tugrik
	MOP Currency = 91  // Pataca
	MRU Currency = 92  // Ouguiya
	MUR Currency = 93  // Mauritius Rupee
	MVR Currency = 94  // Rufiyaa
	MWK Currency = 95  // Malawi Kwacha
	MXN Currency = 96  // Mexican Peso
	MYR Currency = 97  // Malaysian Ringgit
	MZN Currency = 98  // Mozambique Metical
	NAD Currency = 99  // Namibia Dollar
	NGN Currency = 100 // Naira
	NIO Currency = 101 // Cordoba Oro
	NOK Currency = 102 // Norwegian Krone
	NPR Currency = 103 // Nepalese Rupee
	NZD Currency = 104 // New Zealand Dollar
	OMR Currency = 105 // Rial Omani
	PAB Currency = 106 // Balboa
	PEN Currency = 107 // Sol
	PGK Currency = 108 // Kina
	PHP Currency = 109 // Philippine Peso
	PKR Currency = 110 // Pakistan Rupee
	PLN Currency = 111 // Zloty
	PYG Currency = 112 // Guarani
	QAR Currency = 113 // Qatari Rial
	RON Currency = 114 // Leu
	RSD Currency = 115 // Serbian Dinar
	RUB Currency = 116 // Russian Ruble
	RWF Currency = 117 // Rwanda Franc
	SAR Currency = 118 // Saudi Riyal
	SBD Currency = 119 // Solomon Islands Dollar
	SCR Currency = 120 // Seychelles Rupee
	SDG Currency = 121 // Sudanese Pound
	SEK Currency = 122 // Swedish Krona
	SGD Currency = 123 // Singapore Dollar
	SHP Currency = 124 // St. Helena Pound
	SLL Currency = 125 // Leone
	SOS Currency = 126 // Somali Shilling
	SRD Currency = 127 // Surinam Dollar
	SSP Currency = 128 // South Sudanese Pound
	STN Currency = 129 // Dobra
	SYP Currency = 130 // Syrian Pound
	SZL Currency = 131 // Lilangeni
	THB Currency = 132 // Baht
	TJS Currency = 133 // Somoni
	TMT Currency = 134 // Manat
	TND Currency = 135 // Tunisian Dinar
	TOP Currency = 136 // Pa'anga
	TRY Currency = 137 // Turkish Lira
	TTD Currency = 138 // Trinidad and Tobago Dollar
	TWD Currency = 139 // New Taiwan Dollar
	TZS Currency = 140 // Tanzanian Shilling
	UAH Currency = 141 // Ukrainian Hryvnia
	UGX Currency = 142 // Uganda Shilling
	USD Currency = 143 // U.S. Dollar
	UYU Currency = 144 // Peso Uruguayo
	UZS Currency = 145 // Uzbekistan Sum
	VES Currency = 146 // Sovereign Bolivar
	VND Currency = 147 // Dong
	VUV Currency = 148 // Vatu
	WST Currency = 149 // Tala
	XAF Currency = 150 // CFA Franc BEAC
	XCD Currency = 151 // East Caribbean Dollar
	XOF Currency = 152 // CFA Franc BCEAO
	XPF Currency = 153 // CFP Franc
	YER Currency = 154 // Yemeni Rial
	ZAR Currency = 155 // Rand
	ZMW Currency = 156 // Zambian Kwacha
	ZWL Currency = 157 // Zimbabwe Dollar
)

var currLookup = map[string]Currency{
	"XXX": XXX, "xxx": XXX, "999": XXX, // No Currency
	"XTS": XTS, "xts": XTS, "963": XTS, // Test Currency
	"AED": AED, "aed": AED, "784": AED, // U.A.E. Dirham
	"AFN": AFN, "afn": AFN, "971": AFN, // Afghani
	"ALL": ALL, "all": ALL, "008": ALL, // Lek
	"AMD": AMD, "amd": AMD, "051": AMD, // Armenian Dram
	"ANG": ANG, "ang": ANG, "532": ANG, // Netherlands Antillian Guilder
	"AOA": AOA, "aoa": AOA, "973": AOA, // Kwanza
	"ARS": ARS, "ars": ARS, "032": ARS, // Argentine Peso
	"AUD": AUD, "aud": AUD, "036": AUD, // Australian Dollar
	"AWG": AWG, "awg": AWG, "533": AWG, // Aruban Guilder
	"AZN": AZN, "azn": AZN, "944": AZN, // Azerbaijan Manat
	"BAM": BAM, "bam": BAM, "977": BAM, // Convertible Mark
	"BBD": BBD, "bbd": BBD, "052": BBD, // Barbados Dollar
	"BDT": BDT, "bdt": BDT, "050": BDT, // Taka
	"BGN": BGN, "bgn": BGN, "975": BGN, // Bulgarian Lev
	"BHD": BHD, "bhd": BHD, "048": BHD, // Bahraini Dinar
	"BIF": BIF, "bif": BIF, "108": BIF, // Burundi Franc
	"BMD": BMD, "bmd": BMD, "060": BMD, // Bermudian Dollar
	"BND": BND, "bnd": BND, "096": BND, // Brunei Dollar
	"BOB": BOB, "bob": BOB, "068": BOB, // Boliviano
	"BRL": BRL, "brl": BRL, "986": BRL, // Brazilian Real
	"BSD": BSD, "bsd": BSD, "044": BSD, // Bahamian Dollar
	"BTN": BTN, "btn": BTN, "064": BTN, // Bhutan Ngultrum
	"BWP": BWP, "bwp": BWP, "072": BWP, // Pula
	"BYN": BYN, "byn": BYN, "933": BYN, // Belarussian Ruble
	"BZD": BZD, "bzd": BZD, "084": BZD, // Belize Dollar
	"CAD": CAD, "cad": CAD, "124": CAD, // Canadian Dollar
	"CDF": CDF, "cdf": CDF, "976": CDF, // Franc Congolais
	"CHF": CHF, "chf": CHF, "756": CHF, // Swiss Franc
	"CLP": CLP, "clp": CLP, "152": CLP, // Chilean Peso
	"CNY": CNY, "cny": CNY, "156": CNY, // Yuan Renminbi
	"COP": COP, "cop": COP, "170": COP, // Colombian Peso
	"CRC": CRC, "crc": CRC, "188": CRC, // Costa Rican Colon
	"CUP": CUP, "cup": CUP, "192": CUP, // Cuban Peso
	"CVE": CVE, "cve": CVE, "132": CVE, // Cape Verde Escudo
	"CZK": CZK, "czk": CZK, "203": CZK, // Czech Koruna
	"DJF": DJF, "djf": DJF, "262": DJF, // Djibouti Franc
	"DKK": DKK, "dkk": DKK, "208": DKK, // Danish Krone
	"DOP": DOP, "dop": DOP, "214": DOP, // Dominican Peso
	"DZD": DZD, "dzd": DZD, "012": DZD, // Algerian Dinar
	"EGP": EGP, "egp": EGP, "818": EGP, // Egyptian Pound
	"ERN": ERN, "ern": ERN, "232": ERN, // Eritean Nakfa
	"ETB": ETB, "etb": ETB, "230": ETB, // Ethiopian Birr
	"EUR": EUR, "eur": EUR, "978": EUR, // Euro
	"FJD": FJD, "fjd": FJD, "242": FJD, // Fiji Dollar
	"FKP": FKP, "fkp": FKP, "238": FKP, // Falkland Islands Pound
	"GBP": GBP, "gbp": GBP, "826": GBP, // Pound Sterling
	"GEL": GEL, "gel": GEL, "981": GEL, // Lari
	"GHS": GHS, "ghs": GHS, "936": GHS, // Cedi
	"GIP": GIP, "gip": GIP, "292": GIP, // Gibraltar Pound
	"GMD": GMD, "gmd": GMD, "270": GMD, // Dalasi
	"GNF": GNF, "gnf": GNF, "324": GNF, // Guinea Franc
	"GTQ": GTQ, "gtq": GTQ, "320": GTQ, // Quetzal
	"GWP": GWP, "gwp": GWP, "624": GWP, // Guinea-Bissau Peso
	"GYD": GYD, "gyd": GYD, "328": GYD, // Guyana Dollar
	"HKD": HKD, "hkd": HKD, "344": HKD, // Hong Kong Dollar
	"HNL": HNL, "hnl": HNL, "340": HNL, // Lempira
	"HRK": HRK, "hrk": HRK, "191": HRK, // Croatian Kuna
	"HTG": HTG, "htg": HTG, "332": HTG, // Gourde
	"HUF": HUF, "huf": HUF, "348": HUF, // Forint
	"IDR": IDR, "idr": IDR, "360": IDR, // Rupiah
	"ILS": ILS, "ils": ILS, "376": ILS, // Israeli Shequel
	"INR": INR, "inr": INR, "356": INR, // Indian Rupee
	"IQD": IQD, "iqd": IQD, "368": IQD, // Iraqi Dinar
	"IRR": IRR, "irr": IRR, "364": IRR, // Iranian Rial
	"ISK": ISK, "isk": ISK, "352": ISK, // Iceland Krona
	"JMD": JMD, "jmd": JMD, "388": JMD, // Jamaican Dollar
	"JOD": JOD, "jod": JOD, "400": JOD, // Jordanian Dinar
	"JPY": JPY, "jpy": JPY, "392": JPY, // Yen
	"KES": KES, "kes": KES, "404": KES, // Kenyan Shilling
	"KGS": KGS, "kgs": KGS, "417": KGS, // Som
	"KHR": KHR, "khr": KHR, "116": KHR, // Riel
	"KMF": KMF, "kmf": KMF, "174": KMF, // Comoro Franc
	"KPW": KPW, "kpw": KPW, "408": KPW, // North Korean Won
	"KRW": KRW, "krw": KRW, "410": KRW, // Won
	"KWD": KWD, "kwd": KWD, "414": KWD, // Kuwaiti Dinar
	"KYD": KYD, "kyd": KYD, "136": KYD, // Cayman Islands Dollar
	"KZT": KZT, "kzt": KZT, "398": KZT, // Tenge
	"LAK": LAK, "lak": LAK, "418": LAK, // Kip
	"LBP": LBP, "lbp": LBP, "422": LBP, // Lebanese Pound
	"LKR": LKR, "lkr": LKR, "144": LKR, // Sri Lanka Rupee
	"LRD": LRD, "lrd": LRD, "430": LRD, // Liberian Dollar
	"LSL": LSL, "lsl": LSL, "426": LSL, // Lesotho Loti
	"LYD": LYD, "lyd": LYD, "434": LYD, // Libyan Dinar
	"MAD": MAD, "mad": MAD, "504": MAD, // Moroccan Dirham
	"MDL": MDL, "mdl": MDL, "498": MDL, // Moldovan Leu
	"MGA": MGA, "mga": MGA, "969": MGA, // Malagasy Ariary
	"MKD": MKD, "mkd": MKD, "807": MKD, // Denar
	"MMK": MMK, "mmk": MMK, "104": MMK, // Kyat
	"MNT": MNT, "mnt": MNT, "496": MNT, // Tugrik
	"MOP": MOP, "mop": MOP, "446": MOP, // Pataca
	"MRU": MRU, "mru": MRU, "929": MRU, // Ouguiya
	"MUR": MUR, "mur": MUR, "480": MUR, // Mauritius Rupee
	"MVR": MVR, "mvr": MVR, "462": MVR, // Rufiyaa
	"MWK": MWK, "mwk": MWK, "454": MWK, // Malawi Kwacha
	"MXN": MXN, "mxn": MXN, "484": MXN, // Mexican Peso
	"MYR": MYR, "myr": MYR, "458": MYR, // Malaysian Ringgit
	"MZN": MZN, "mzn": MZN, "943": MZN, // Mozambique Metical
	"NAD": NAD, "nad": NAD, "516": NAD, // Namibia Dollar
	"NGN": NGN, "ngn": NGN, "566": NGN, // Naira
	"NIO": NIO, "nio": NIO, "558": NIO, // Cordoba Oro
	"NOK": NOK, "nok": NOK, "578": NOK, // Norwegian Krone
	"NPR": NPR, "npr": NPR, "524": NPR, // Nepalese Rupee
	"NZD": NZD, "nzd": NZD, "554": NZD, // New Zealand Dollar
	"OMR": OMR, "omr": OMR, "512": OMR, // Rial Omani
	"PAB": PAB, "pab": PAB, "590": PAB, // Balboa
	"PEN": PEN, "pen": PEN, "604": PEN, // Sol
	"PGK": PGK, "pgk": PGK, "598": PGK, // Kina
	"PHP": PHP, "php": PHP, "608": PHP, // Philippine Peso
	"PKR": PKR, "pkr": PKR, "586": PKR, // Pakistan Rupee
	"PLN": PLN, "pln": PLN, "985": PLN, // Zloty
	"PYG": PYG, "pyg": PYG, "600": PYG, // Guarani
	"QAR": QAR, "qar": QAR, "634": QAR, // Qatari Rial
	"RON": RON, "ron": RON, "946": RON, // Leu
	"RSD": RSD, "rsd": RSD, "941": RSD, // Serbian Dinar
	"RUB": RUB, "rub": RUB, "643": RUB, // Russian Ruble
	"RWF": RWF, "rwf": RWF, "646": RWF, // Rwanda Franc
	"SAR": SAR, "sar": SAR, "682": SAR, // Saudi Riyal
	"SBD": SBD, "sbd": SBD, "090": SBD, // Solomon Islands Dollar
	"SCR": SCR, "scr": SCR, "690": SCR, // Seychelles Rupee
	"SDG": SDG, "sdg": SDG, "938": SDG, // Sudanese Pound
	"SEK": SEK, "sek": SEK, "752": SEK, // Swedish Krona
	"SGD": SGD, "sgd": SGD, "702": SGD, // Singapore Dollar
	"SHP": SHP, "shp": SHP, "654": SHP, // St. Helena Pound
	"SLL": SLL, "sll": SLL, "694": SLL, // Leone
	"SOS": SOS, "sos": SOS, "706": SOS, // Somali Shilling
	"SRD": SRD, "srd": SRD, "968": SRD, // Surinam Dollar
	"SSP": SSP, "ssp": SSP, "728": SSP, // South Sudanese Pound
	"STN": STN, "stn": STN, "930": STN, // Dobra
	"SYP": SYP, "syp": SYP, "760": SYP, // Syrian Pound
	"SZL": SZL, "szl": SZL, "748": SZL, // Lilangeni
	"THB": THB, "thb": THB, "764": THB, // Baht
	"TJS": TJS, "tjs": TJS, "972": TJS, // Somoni
	"TMT": TMT, "tmt": TMT, "934": TMT, // Manat
	"TND": TND, "tnd": TND, "788": TND, // Tunisian Dinar
	"TOP": TOP, "top": TOP, "776": TOP, // Pa'anga
	"TRY": TRY, "try": TRY, "949": TRY, // Turkish Lira
	"TTD": TTD, "ttd": TTD, "780": TTD, // Trinidad and Tobago Dollar
	"TWD": TWD, "twd": TWD, "901": TWD, // New Taiwan Dollar
	"TZS": TZS, "tzs": TZS, "834": TZS, // Tanzanian Shilling
	"UAH": UAH, "uah": UAH, "980": UAH, // Ukrainian Hryvnia
	"UGX": UGX, "ugx": UGX, "800": UGX, // Uganda Shilling
	"USD": USD, "usd": USD, "840": USD, // U.S. Dollar
	"UYU": UYU, "uyu": UYU, "858": UYU, // Peso Uruguayo
	"UZS": UZS, "uzs": UZS, "860": UZS, // Uzbekistan Sum
	"VES": VES, "ves": VES, "928": VES, // Sovereign Bolivar
	"VND": VND, "vnd": VND, "704": VND, // Dong
	"VUV": VUV, "vuv": VUV, "548": VUV, // Vatu
	"WST": WST, "wst": WST, "882": WST, // Tala
	"XAF": XAF, "xaf": XAF, "950": XAF, // CFA Franc BEAC
	"XCD": XCD, "xcd": XCD, "951": XCD, // East Caribbean Dollar
	"XOF": XOF, "xof": XOF, "952": XOF, // CFA Franc BCEAO
	"XPF": XPF, "xpf": XPF, "953": XPF, // CFP Franc
	"YER": YER, "yer": YER, "886": YER, // Yemeni Rial
	"ZAR": ZAR, "zar": ZAR, "710": ZAR, // Rand
	"ZMW": ZMW, "zmw": ZMW, "967": ZMW, // Zambian Kwacha
	"ZWL": ZWL, "zwl": ZWL, "932": ZWL, // Zimbabwe Dollar
}

var scaleLookup = [...]int8{
	0, // No Currency
	2, // Test Currency
	2, // U.A.E. Dirham
	2, // Afghani
	2, // Lek
	2, // Armenian Dram
	2, // Netherlands Antillian Guilder
	2, // Kwanza
	2, // Argentine Peso
	2, // Australian Dollar
	2, // Aruban Guilder
	2, // Azerbaijan Manat
	2, // Convertible Mark
	2, // Barbados Dollar
	2, // Taka
	2, // Bulgarian Lev
	3, // Bahraini Dinar
	0, // Burundi Franc
	2, // Bermudian Dollar
	2, // Brunei Dollar
	2, // Boliviano
	2, // Brazilian Real
	2, // Bahamian Dollar
	2, // Bhutan Ngultrum
	2, // Pula
	2, // Belarussian Ruble
	2, // Belize Dollar
	2, // Canadian Dollar
	2, // Franc Congolais
	2, // Swiss Franc
	0, // Chilean Peso
	2, // Yuan Renminbi
	2, // Colombian Peso
	2, // Costa Rican Colon
	2, // Cuban Peso
	2, // Cape Verde Escudo
	2, // Czech Koruna
	0, // Djibouti Franc
	2, // Danish Krone
	2, // Dominican Peso
	2, // Algerian Dinar
	2, // Egyptian Pound
	2, // Eritean Nakfa
	2, // Ethiopian Birr
	2, // Euro
	2, // Fiji Dollar
	2, // Falkland Islands Pound
	2, // Pound Sterling
	2, // Lari
	2, // Cedi
	2, // Gibraltar Pound
	2, // Dalasi
	0, // Guinea Franc
	2, // Quetzal
	2, // Guinea-Bissau Peso
	2, // Guyana Dollar
	2, // Hong Kong Dollar
	2, // Lempira
	2, // Croatian Kuna
	2, // Gourde
	2, // Forint
	2, // Rupiah
	2, // Israeli Shequel
	2, // Indian Rupee
	3, // Iraqi Dinar
	2, // Iranian Rial
	2, // Iceland Krona
	2, // Jamaican Dollar
	3, // Jordanian Dinar
	0, // Yen
	2, // Kenyan Shilling
	2, // Som
	2, // Riel
	0, // Comoro Franc
	2, // North Korean Won
	0, // Won
	3, // Kuwaiti Dinar
	2, // Cayman Islands Dollar
	2, // Tenge
	2, // Kip
	2, // Lebanese Pound
	2, // Sri Lanka Rupee
	2, // Liberian Dollar
	2, // Lesotho Loti
	3, // Libyan Dinar
	2, // Moroccan Dirham
	2, // Moldovan Leu
	2, // Malagasy Ariary
	2, // Denar
	2, // Kyat
	2, // Tugrik
	2, // Pataca
	2, // Ouguiya
	2, // Mauritius Rupee
	2, // Rufiyaa
	2, // Malawi Kwacha
	2, // Mexican Peso
	2, // Malaysian Ringgit
	2, // Mozambique Metical
	2, // Namibia Dollar
	2, // Naira
	2, // Cordoba Oro
	2, // Norwegian Krone
	2, // Nepalese Rupee
	2, // New Zealand Dollar
	3, // Rial Omani
	2, // Balboa
	2, // Sol
	2, // Kina
	2, // Philippine Peso
	2, // Pakistan Rupee
	2, // Zloty
	0, // Guarani
	2, // Qatari Rial
	2, // Leu
	2, // Serbian Dinar
	2, // Russian Ruble
	0, // Rwanda Franc
	2, // Saudi Riyal
	2, // Solomon Islands Dollar
	2, // Seychelles Rupee
	2, // Sudanese Pound
	2, // Swedish Krona
	2, // Singapore Dollar
	2, // St. Helena Pound
	2, // Leone
	2, // Somali Shilling
	2, // Surinam Dollar
	2, // South Sudanese Pound
	2, // Dobra
	2, // Syrian Pound
	2, // Lilangeni
	2, // Baht
	2, // Somoni
	2, // Manat
	3, // Tunisian Dinar
	2, // Pa'anga
	2, // Turkish Lira
	2, // Trinidad and Tobago Dollar
	2, // New Taiwan Dollar
	2, // Tanzanian Shilling
	2, // Ukrainian Hryvnia
	0, // Uganda Shilling
	2, // U.S. Dollar
	2, // Peso Uruguayo
	2, // Uzbekistan Sum
	2, // Sovereign Bolivar
	0, // Dong
	0, // Vatu
	2, // Tala
	0, // CFA Franc BEAC
	2, // East Caribbean Dollar
	0, // CFA Franc BCEAO
	0, // CFP Franc
	2, // Yemeni Rial
	2, // Rand
	2, // Zambian Kwacha
	2, // Zimbabwe Dollar
}

var numLookup = [...]string{
	"999", // No Currency
	"963", // Test Currency
	"784", // U.A.E. Dirham
	"971", // Afghani
	"008", // Lek
	"051", // Armenian Dram
	"532", // Netherlands Antillian Guilder
	"973", // Kwanza
	"032", // Argentine Peso
	"036", // Australian Dollar
	"533", // Aruban Guilder
	"944", // Azerbaijan Manat
	"977", // Convertible Mark
	"052", // Barbados Dollar
	"050", // Taka
	"975", // Bulgarian Lev
	"048", // Bahraini Dinar
	"108", // Burundi Franc
	"060", // Bermudian Dollar
	"096", // Brunei Dollar
	"068", // Boliviano
	"986", // Brazilian Real
	"044", // Bahamian Dollar
	"064", // Bhutan Ngultrum
	"072", // Pula
	"933", // Belarussian Ruble
	"084", // Belize Dollar
	"124", // Canadian Dollar
	"976", // Franc Congolais
	"756", // Swiss Franc
	"152", // Chilean Peso
	"156", // Yuan Renminbi
	"170", // Colombian Peso
	"188", // Costa Rican Colon
	"192", // Cuban Peso
	"132", // Cape Verde Escudo
	"203", // Czech Koruna
	"262", // Djibouti Franc
	"208", // Danish Krone
	"214", // Dominican Peso
	"012", // Algerian Dinar
	"818", // Egyptian Pound
	"232", // Eritean Nakfa
	"230", // Ethiopian Birr
	"978", // Euro
	"242", // Fiji Dollar
	"238", // Falkland Islands Pound
	"826", // Pound Sterling
	"981", // Lari
	"936", // Cedi
	"292", // Gibraltar Pound
	"270", // Dalasi
	"324", // Guinea Franc
	"320", // Quetzal
	"624", // Guinea-Bissau Peso
	"328", // Guyana Dollar
	"344", // Hong Kong Dollar
	"340", // Lempira
	"191", // Croatian Kuna
	"332", // Gourde
	"348", // Forint
	"360", // Rupiah
	"376", // Israeli Shequel
	"356", // Indian Rupee
	"368", // Iraqi Dinar
	"364", // Iranian Rial
	"352", // Iceland Krona
	"388", // Jamaican Dollar
	"400", // Jordanian Dinar
	"392", // Yen
	"404", // Kenyan Shilling
	"417", // Som
	"116", // Riel
	"174", // Comoro Franc
	"408", // North Korean Won
	"410", // Won
	"414", // Kuwaiti Dinar
	"136", // Cayman Islands Dollar
	"398", // Tenge
	"418", // Kip
	"422", // Lebanese Pound
	"144", // Sri Lanka Rupee
	"430", // Liberian Dollar
	"426", // Lesotho Loti
	"434", // Libyan Dinar
	"504", // Moroccan Dirham
	"498", // Moldovan Leu
	"969", // Malagasy Ariary
	"807", // Denar
	"104", // Kyat
	"496", // Tugrik
	"446", // Pataca
	"929", // Ouguiya
	"480", // Mauritius Rupee
	"462", // Rufiyaa
	"454", // Malawi Kwacha
	"484", // Mexican Peso
	"458", // Malaysian Ringgit
	"943", // Mozambique Metical
	"516", // Namibia Dollar
	"566", // Naira
	"558", // Cordoba Oro
	"578", // Norwegian Krone
	"524", // Nepalese Rupee
	"554", // New Zealand Dollar
	"512", // Rial Omani
	"590", // Balboa
	"604", // Sol
	"598", // Kina
	"608", // Philippine Peso
	"586", // Pakistan Rupee
	"985", // Zloty
	"600", // Guarani
	"634", // Qatari Rial
	"946", // Leu
	"941", // Serbian Dinar
	"643", // Russian Ruble
	"646", // Rwanda Franc
	"682", // Saudi Riyal
	"090", // Solomon Islands Dollar
	"690", // Seychelles Rupee
	"938", // Sudanese Pound
	"752", // Swedish Krona
	"702", // Singapore Dollar
	"654", // St. Helena Pound
	"694", // Leone
	"706", // Somali Shilling
	"968", // Surinam Dollar
	"728", // South Sudanese Pound
	"930", // Dobra
	"760", // Syrian Pound
	"748", // Lilangeni
	"764", // Baht
	"972", // Somoni
	"934", // Manat
	"788", // Tunisian Dinar
	"776", // Pa'anga
	"949", // Turkish Lira
	"780", // Trinidad and Tobago Dollar
	"901", // New Taiwan Dollar
	"834", // Tanzanian Shilling
	"980", // Ukrainian Hryvnia
	"800", // Uganda Shilling
	"840", // U.S. Dollar
	"858", // Peso Uruguayo
	"860", // Uzbekistan Sum
	"928", // Sovereign Bolivar
	"704", // Dong
	"548", // Vatu
	"882", // Tala
	"950", // CFA Franc BEAC
	"951", // East Caribbean Dollar
	"952", // CFA Franc BCEAO
	"953", // CFP Franc
	"886", // Yemeni Rial
	"710", // Rand
	"967", // Zambian Kwacha
	"932", // Zimbabwe Dollar
}

var codeLookup = [...]string{
	"XXX", // No Currency
	"XTS", // Test Currency
	"AED", // U.A.E. Dirham
	"AFN", // Afghani
	"ALL", // Lek
	"AMD", // Armenian Dram
	"ANG", // Netherlands Antillian Guilder
	"AOA", // Kwanza
	"ARS", // Argentine Peso
	"AUD", // Australian Dollar
	"AWG", // Aruban Guilder
	"AZN", // Azerbaijan Manat
	"BAM", // Convertible Mark
	"BBD", // Barbados Dollar
	"BDT", // Taka
	"BGN", // Bulgarian Lev
	"BHD", // Bahraini Dinar
	"BIF", // Burundi Franc
	"BMD", // Bermudian Dollar
	"BND", // Brunei Dollar
	"BOB", // Boliviano
	"BRL", // Brazilian Real
	"BSD", // Bahamian Dollar
	"BTN", // Bhutan Ngultrum
	"BWP", // Pula
	"BYN", // Belarussian Ruble
	"BZD", // Belize Dollar
	"CAD", // Canadian Dollar
	"CDF", // Franc Congolais
	"CHF", // Swiss Franc
	"CLP", // Chilean Peso
	"CNY", // Yuan Renminbi
	"COP", // Colombian Peso
	"CRC", // Costa Rican Colon
	"CUP", // Cuban Peso
	"CVE", // Cape Verde Escudo
	"CZK", // Czech Koruna
	"DJF", // Djibouti Franc
	"DKK", // Danish Krone
	"DOP", // Dominican Peso
	"DZD", // Algerian Dinar
	"EGP", // Egyptian Pound
	"ERN", // Eritean Nakfa
	"ETB", // Ethiopian Birr
	"EUR", // Euro
	"FJD", // Fiji Dollar
	"FKP", // Falkland Islands Pound
	"GBP", // Pound Sterling
	"GEL", // Lari
	"GHS", // Cedi
	"GIP", // Gibraltar Pound
	"GMD", // Dalasi
	"GNF", // Guinea Franc
	"GTQ", // Quetzal
	"GWP", // Guinea-Bissau Peso
	"GYD", // Guyana Dollar
	"HKD", // Hong Kong Dollar
	"HNL", // Lempira
	"HRK", // Croatian Kuna
	"HTG", // Gourde
	"HUF", // Forint
	"IDR", // Rupiah
	"ILS", // Israeli Shequel
	"INR", // Indian Rupee
	"IQD", // Iraqi Dinar
	"IRR", // Iranian Rial
	"ISK", // Iceland Krona
	"JMD", // Jamaican Dollar
	"JOD", // Jordanian Dinar
	"JPY", // Yen
	"KES", // Kenyan Shilling
	"KGS", // Som
	"KHR", // Riel
	"KMF", // Comoro Franc
	"KPW", // North Korean Won
	"KRW", // Won
	"KWD", // Kuwaiti Dinar
	"KYD", // Cayman Islands Dollar
	"KZT", // Tenge
	"LAK", // Kip
	"LBP", // Lebanese Pound
	"LKR", // Sri Lanka Rupee
	"LRD", // Liberian Dollar
	"LSL", // Lesotho Loti
	"LYD", // Libyan Dinar
	"MAD", // Moroccan Dirham
	"MDL", // Moldovan Leu
	"MGA", // Malagasy Ariary
	"MKD", // Denar
	"MMK", // Kyat
	"MNT", // Tugrik
	"MOP", // Pataca
	"MRU", // Ouguiya
	"MUR", // Mauritius Rupee
	"MVR", // Rufiyaa
	"MWK", // Malawi Kwacha
	"MXN", // Mexican Peso
	"MYR", // Malaysian Ringgit
	"MZN", // Mozambique Metical
	"NAD", // Namibia Dollar
	"NGN", // Naira
	"NIO", // Cordoba Oro
	"NOK", // Norwegian Krone
	"NPR", // Nepalese Rupee
	"NZD", // New Zealand Dollar
	"OMR", // Rial Omani
	"PAB", // Balboa
	"PEN", // Sol
	"PGK", // Kina
	"PHP", // Philippine Peso
	"PKR", // Pakistan Rupee
	"PLN", // Zloty
	"PYG", // Guarani
	"QAR", // Qatari Rial
	"RON", // Leu
	"RSD", // Serbian Dinar
	"RUB", // Russian Ruble
	"RWF", // Rwanda Franc
	"SAR", // Saudi Riyal
	"SBD", // Solomon Islands Dollar
	"SCR", // Seychelles Rupee
	"SDG", // Sudanese Pound
	"SEK", // Swedish Krona
	"SGD", // Singapore Dollar
	"SHP", // St. Helena Pound
	"SLL", // Leone
	"SOS", // Somali Shilling
	"SRD", // Surinam Dollar
	"SSP", // South Sudanese Pound
	"STN", // Dobra
	"SYP", // Syrian Pound
	"SZL", // Lilangeni
	"THB", // Baht
	"TJS", // Somoni
	"TMT", // Manat
	"TND", // Tunisian Dinar
	"TOP", // Pa'anga
	"TRY", // Turkish Lira
	"TTD", // Trinidad and Tobago Dollar
	"TWD", // New Taiwan Dollar
	"TZS", // Tanzanian Shilling
	"UAH", // Ukrainian Hryvnia
	"UGX", // Uganda Shilling
	"USD", // U.S. Dollar
	"UYU", // Peso Uruguayo
	"UZS", // Uzbekistan Sum
	"VES", // Sovereign Bolivar
	"VND", // Dong
	"VUV", // Vatu
	"WST", // Tala
	"XAF", // CFA Franc BEAC
	"XCD", // East Caribbean Dollar
	"XOF", // CFA Franc BCEAO
	"XPF", // CFP Franc
	"YER", // Yemeni Rial
	"ZAR", // Rand
	"ZMW", // Zambian Kwacha
	"ZWL", // Zimbabwe Dollar
}
