// Code generated by scripts/currency/codegen.go. DO NOT EDIT.
// Any changes made to this file will be overwritten the next time it is generated.

package money

const (
	XXX Currency = 0   // No Currency
	XTS Currency = 1   // Test Currency
	AED Currency = 2   // U.A.E. Dirham
	AFN Currency = 3   // Afghani
	ALL Currency = 4   // Lek
	AMD Currency = 5   // Armenian Dram
	ANG Currency = 6   // Netherlands Antillian Guilder
	AOA Currency = 7   // Kwanza
	ARS Currency = 8   // Argentine Peso
	AUD Currency = 9   // Australian Dollar
	AWG Currency = 10  // Aruban Guilder
	AZN Currency = 11  // Azerbaijan Manat
	BAM Currency = 12  // Convertible Mark
	BBD Currency = 13  // Barbados Dollar
	BDT Currency = 14  // Taka
	BGN Currency = 15  // Bulgarian Lev
	BHD Currency = 16  // Bahraini Dinar
	BIF Currency = 17  // Burundi Franc
	BMD Currency = 18  // Bermudian Dollar
	BND Currency = 19  // Brunei Dollar
	BOB Currency = 20  // Boliviano
	BRL Currency = 21  // Brazilian Real
	BSD Currency = 22  // Bahamian Dollar
	BTN Currency = 23  // Bhutan Ngultrum
	BWP Currency = 24  // Pula
	BYN Currency = 25  // Belarussian Ruble
	BZD Currency = 26  // Belize Dollar
	CAD Currency = 27  // Canadian Dollar
	CDF Currency = 28  // Franc Congolais
	CHF Currency = 29  // Swiss Franc
	CLP Currency = 30  // Chilean Peso
	CNY Currency = 31  // Yuan Renminbi
	COP Currency = 32  // Colombian Peso
	CRC Currency = 33  // Costa Rican Colon
	CUP Currency = 34  // Cuban Peso
	CVE Currency = 35  // Cape Verde Escudo
	CZK Currency = 36  // Czech Koruna
	DJF Currency = 37  // Djibouti Franc
	DKK Currency = 38  // Danish Krone
	DOP Currency = 39  // Dominican Peso
	DZD Currency = 40  // Algerian Dinar
	EGP Currency = 41  // Egyptian Pound
	ERN Currency = 42  // Eritean Nakfa
	ETB Currency = 43  // Ethiopian Birr
	EUR Currency = 44  // Euro
	FJD Currency = 45  // Fiji Dollar
	FKP Currency = 46  // Falkland Islands Pound
	GBP Currency = 47  // Pound Sterling
	GEL Currency = 48  // Lari
	GHS Currency = 49  // Cedi
	GIP Currency = 50  // Gibraltar Pound
	GMD Currency = 51  // Dalasi
	GNF Currency = 52  // Guinea Franc
	GTQ Currency = 53  // Quetzal
	GWP Currency = 54  // Guinea-Bissau Peso
	GYD Currency = 55  // Guyana Dollar
	HKD Currency = 56  // Hong Kong Dollar
	HNL Currency = 57  // Lempira
	HRK Currency = 58  // Croatian Kuna
	HTG Currency = 59  // Gourde
	HUF Currency = 60  // Forint
	IDR Currency = 61  // Rupiah
	ILS Currency = 62  // Israeli Shequel
	INR Currency = 63  // Indian Rupee
	IQD Currency = 64  // Iraqi Dinar
	IRR Currency = 65  // Iranian Rial
	ISK Currency = 66  // Iceland Krona
	JMD Currency = 67  // Jamaican Dollar
	JOD Currency = 68  // Jordanian Dinar
	JPY Currency = 69  // Yen
	KES Currency = 70  // Kenyan Shilling
	KGS Currency = 71  // Som
	KHR Currency = 72  // Riel
	KMF Currency = 73  // Comoro Franc
	KPW Currency = 74  // North Korean Won
	KRW Currency = 75  // Won
	KWD Currency = 76  // Kuwaiti Dinar
	KYD Currency = 77  // Cayman Islands Dollar
	KZT Currency = 78  // Tenge
	LAK Currency = 79  // Kip
	LBP Currency = 80  // Lebanese Pound
	LKR Currency = 81  // Sri Lanka Rupee
	LRD Currency = 82  // Liberian Dollar
	LSL Currency = 83  // Lesotho Loti
	LYD Currency = 84  // Libyan Dinar
	MAD Currency = 85  // Moroccan Dirham
	MDL Currency = 86  // Moldovan Leu
	MGA Currency = 87  // Malagasy Ariary
	MKD Currency = 88  // Denar
	MMK Currency = 89  // Kyat
	MNT Currency = 90  // Tugrik
	MOP Currency = 91  // Pataca
	MRU Currency = 92  // Ouguiya
	MUR Currency = 93  // Mauritius Rupee
	MVR Currency = 94  // Rufiyaa
	MWK Currency = 95  // Malawi Kwacha
	MXN Currency = 96  // Mexican Peso
	MYR Currency = 97  // Malaysian Ringgit
	MZN Currency = 98  // Mozambique Metical
	NAD Currency = 99  // Namibia Dollar
	NGN Currency = 100 // Naira
	NIO Currency = 101 // Cordoba Oro
	NOK Currency = 102 // Norwegian Krone
	NPR Currency = 103 // Nepalese Rupee
	NZD Currency = 104 // New Zealand Dollar
	OMR Currency = 105 // Rial Omani
	PAB Currency = 106 // Balboa
	PEN Currency = 107 // Sol
	PGK Currency = 108 // Kina
	PHP Currency = 109 // Philippine Peso
	PKR Currency = 110 // Pakistan Rupee
	PLN Currency = 111 // Zloty
	PYG Currency = 112 // Guarani
	QAR Currency = 113 // Qatari Rial
	RON Currency = 114 // Leu
	RSD Currency = 115 // Serbian Dinar
	RUB Currency = 116 // Russian Ruble
	RWF Currency = 117 // Rwanda Franc
	SAR Currency = 118 // Saudi Riyal
	SBD Currency = 119 // Solomon Islands Dollar
	SCR Currency = 120 // Seychelles Rupee
	SDG Currency = 121 // Sudanese Pound
	SEK Currency = 122 // Swedish Krona
	SGD Currency = 123 // Singapore Dollar
	SHP Currency = 124 // St. Helena Pound
	SLL Currency = 125 // Leone
	SOS Currency = 126 // Somali Shilling
	SRD Currency = 127 // Surinam Dollar
	SSP Currency = 128 // South Sudanese Pound
	STN Currency = 129 // Dobra
	SYP Currency = 130 // Syrian Pound
	SZL Currency = 131 // Lilangeni
	THB Currency = 132 // Baht
	TJS Currency = 133 // Somoni
	TMT Currency = 134 // Manat
	TND Currency = 135 // Tunisian Dinar
	TOP Currency = 136 // Pa'anga
	TRY Currency = 137 // Turkish Lira
	TTD Currency = 138 // Trinidad and Tobago Dollar
	TWD Currency = 139 // New Taiwan Dollar
	TZS Currency = 140 // Tanzanian Shilling
	UAH Currency = 141 // Ukrainian Hryvnia
	UGX Currency = 142 // Uganda Shilling
	USD Currency = 143 // U.S. Dollar
	UYU Currency = 144 // Peso Uruguayo
	UZS Currency = 145 // Uzbekistan Sum
	VES Currency = 146 // Sovereign Bolivar
	VND Currency = 147 // Dong
	VUV Currency = 148 // Vatu
	WST Currency = 149 // Tala
	XAF Currency = 150 // CFA Franc BEAC
	XCD Currency = 151 // East Caribbean Dollar
	XOF Currency = 152 // CFA Franc BCEAO
	XPF Currency = 153 // CFP Franc
	YER Currency = 154 // Yemeni Rial
	ZAR Currency = 155 // Rand
	ZMW Currency = 156 // Zambian Kwacha
	ZWL Currency = 157 // Zimbabwe Dollar
)

var currLookup = map[string]Currency{
	"XXX": XXX, "xxx": XXX, "999": XXX, // No Currency
	"XTS": XTS, "xts": XTS, "963": XTS, // Test Currency
	"AED": AED, "aed": AED, "784": AED, // U.A.E. Dirham
	"AFN": AFN, "afn": AFN, "971": AFN, // Afghani
	"ALL": ALL, "all": ALL, "008": ALL, // Lek
	"AMD": AMD, "amd": AMD, "051": AMD, // Armenian Dram
	"ANG": ANG, "ang": ANG, "532": ANG, // Netherlands Antillian Guilder
	"AOA": AOA, "aoa": AOA, "973": AOA, // Kwanza
	"ARS": ARS, "ars": ARS, "032": ARS, // Argentine Peso
	"AUD": AUD, "aud": AUD, "036": AUD, // Australian Dollar
	"AWG": AWG, "awg": AWG, "533": AWG, // Aruban Guilder
	"AZN": AZN, "azn": AZN, "944": AZN, // Azerbaijan Manat
	"BAM": BAM, "bam": BAM, "977": BAM, // Convertible Mark
	"BBD": BBD, "bbd": BBD, "052": BBD, // Barbados Dollar
	"BDT": BDT, "bdt": BDT, "050": BDT, // Taka
	"BGN": BGN, "bgn": BGN, "975": BGN, // Bulgarian Lev
	"BHD": BHD, "bhd": BHD, "048": BHD, // Bahraini Dinar
	"BIF": BIF, "bif": BIF, "108": BIF, // Burundi Franc
	"BMD": BMD, "bmd": BMD, "060": BMD, // Bermudian Dollar
	"BND": BND, "bnd": BND, "096": BND, // Brunei Dollar
	"BOB": BOB, "bob": BOB, "068": BOB, // Boliviano
	"BRL": BRL, "brl": BRL, "986": BRL, // Brazilian Real
	"BSD": BSD, "bsd": BSD, "044": BSD, // Bahamian Dollar
	"BTN": BTN, "btn": BTN, "064": BTN, // Bhutan Ngultrum
	"BWP": BWP, "bwp": BWP, "072": BWP, // Pula
	"BYN": BYN, "byn": BYN, "933": BYN, // Belarussian Ruble
	"BZD": BZD, "bzd": BZD, "084": BZD, // Belize Dollar
	"CAD": CAD, "cad": CAD, "124": CAD, // Canadian Dollar
	"CDF": CDF, "cdf": CDF, "976": CDF, // Franc Congolais
	"CHF": CHF, "chf": CHF, "756": CHF, // Swiss Franc
	"CLP": CLP, "clp": CLP, "152": CLP, // Chilean Peso
	"CNY": CNY, "cny": CNY, "156": CNY, // Yuan Renminbi
	"COP": COP, "cop": COP, "170": COP, // Colombian Peso
	"CRC": CRC, "crc": CRC, "188": CRC, // Costa Rican Colon
	"CUP": CUP, "cup": CUP, "192": CUP, // Cuban Peso
	"CVE": CVE, "cve": CVE, "132": CVE, // Cape Verde Escudo
	"CZK": CZK, "czk": CZK, "203": CZK, // Czech Koruna
	"DJF": DJF, "djf": DJF, "262": DJF, // Djibouti Franc
	"DKK": DKK, "dkk": DKK, "208": DKK, // Danish Krone
	"DOP": DOP, "dop": DOP, "214": DOP, // Dominican Peso
	"DZD": DZD, "dzd": DZD, "012": DZD, // Algerian Dinar
	"EGP": EGP, "egp": EGP, "818": EGP, // Egyptian Pound
	"ERN": ERN, "ern": ERN, "232": ERN, // Eritean Nakfa
	"ETB": ETB, "etb": ETB, "230": ETB, // Ethiopian Birr
	"EUR": EUR, "eur": EUR, "978": EUR, // Euro
	"FJD": FJD, "fjd": FJD, "242": FJD, // Fiji Dollar
	"FKP": FKP, "fkp": FKP, "238": FKP, // Falkland Islands Pound
	"GBP": GBP, "gbp": GBP, "826": GBP, // Pound Sterling
	"GEL": GEL, "gel": GEL, "981": GEL, // Lari
	"GHS": GHS, "ghs": GHS, "936": GHS, // Cedi
	"GIP": GIP, "gip": GIP, "292": GIP, // Gibraltar Pound
	"GMD": GMD, "gmd": GMD, "270": GMD, // Dalasi
	"GNF": GNF, "gnf": GNF, "324": GNF, // Guinea Franc
	"GTQ": GTQ, "gtq": GTQ, "320": GTQ, // Quetzal
	"GWP": GWP, "gwp": GWP, "624": GWP, // Guinea-Bissau Peso
	"GYD": GYD, "gyd": GYD, "328": GYD, // Guyana Dollar
	"HKD": HKD, "hkd": HKD, "344": HKD, // Hong Kong Dollar
	"HNL": HNL, "hnl": HNL, "340": HNL, // Lempira
	"HRK": HRK, "hrk": HRK, "191": HRK, // Croatian Kuna
	"HTG": HTG, "htg": HTG, "332": HTG, // Gourde
	"HUF": HUF, "huf": HUF, "348": HUF, // Forint
	"IDR": IDR, "idr": IDR, "360": IDR, // Rupiah
	"ILS": ILS, "ils": ILS, "376": ILS, // Israeli Shequel
	"INR": INR, "inr": INR, "356": INR, // Indian Rupee
	"IQD": IQD, "iqd": IQD, "368": IQD, // Iraqi Dinar
	"IRR": IRR, "irr": IRR, "364": IRR, // Iranian Rial
	"ISK": ISK, "isk": ISK, "352": ISK, // Iceland Krona
	"JMD": JMD, "jmd": JMD, "388": JMD, // Jamaican Dollar
	"JOD": JOD, "jod": JOD, "400": JOD, // Jordanian Dinar
	"JPY": JPY, "jpy": JPY, "392": JPY, // Yen
	"KES": KES, "kes": KES, "404": KES, // Kenyan Shilling
	"KGS": KGS, "kgs": KGS, "417": KGS, // Som
	"KHR": KHR, "khr": KHR, "116": KHR, // Riel
	"KMF": KMF, "kmf": KMF, "174": KMF, // Comoro Franc
	"KPW": KPW, "kpw": KPW, "408": KPW, // North Korean Won
	"KRW": KRW, "krw": KRW, "410": KRW, // Won
	"KWD": KWD, "kwd": KWD, "414": KWD, // Kuwaiti Dinar
	"KYD": KYD, "kyd": KYD, "136": KYD, // Cayman Islands Dollar
	"KZT": KZT, "kzt": KZT, "398": KZT, // Tenge
	"LAK": LAK, "lak": LAK, "418": LAK, // Kip
	"LBP": LBP, "lbp": LBP, "422": LBP, // Lebanese Pound
	"LKR": LKR, "lkr": LKR, "144": LKR, // Sri Lanka Rupee
	"LRD": LRD, "lrd": LRD, "430": LRD, // Liberian Dollar
	"LSL": LSL, "lsl": LSL, "426": LSL, // Lesotho Loti
	"LYD": LYD, "lyd": LYD, "434": LYD, // Libyan Dinar
	"MAD": MAD, "mad": MAD, "504": MAD, // Moroccan Dirham
	"MDL": MDL, "mdl": MDL, "498": MDL, // Moldovan Leu
	"MGA": MGA, "mga": MGA, "969": MGA, // Malagasy Ariary
	"MKD": MKD, "mkd": MKD, "807": MKD, // Denar
	"MMK": MMK, "mmk": MMK, "104": MMK, // Kyat
	"MNT": MNT, "mnt": MNT, "496": MNT, // Tugrik
	"MOP": MOP, "mop": MOP, "446": MOP, // Pataca
	"MRU": MRU, "mru": MRU, "929": MRU, // Ouguiya
	"MUR": MUR, "mur": MUR, "480": MUR, // Mauritius Rupee
	"MVR": MVR, "mvr": MVR, "462": MVR, // Rufiyaa
	"MWK": MWK, "mwk": MWK, "454": MWK, // Malawi Kwacha
	"MXN": MXN, "mxn": MXN, "484": MXN, // Mexican Peso
	"MYR": MYR, "myr": MYR, "458": MYR, // Malaysian Ringgit
	"MZN": MZN, "mzn": MZN, "943": MZN, // Mozambique Metical
	"NAD": NAD, "nad": NAD, "516": NAD, // Namibia Dollar
	"NGN": NGN, "ngn": NGN, "566": NGN, // Naira
	"NIO": NIO, "nio": NIO, "558": NIO, // Cordoba Oro
	"NOK": NOK, "nok": NOK, "578": NOK, // Norwegian Krone
	"NPR": NPR, "npr": NPR, "524": NPR, // Nepalese Rupee
	"NZD": NZD, "nzd": NZD, "554": NZD, // New Zealand Dollar
	"OMR": OMR, "omr": OMR, "512": OMR, // Rial Omani
	"PAB": PAB, "pab": PAB, "590": PAB, // Balboa
	"PEN": PEN, "pen": PEN, "604": PEN, // Sol
	"PGK": PGK, "pgk": PGK, "598": PGK, // Kina
	"PHP": PHP, "php": PHP, "608": PHP, // Philippine Peso
	"PKR": PKR, "pkr": PKR, "586": PKR, // Pakistan Rupee
	"PLN": PLN, "pln": PLN, "985": PLN, // Zloty
	"PYG": PYG, "pyg": PYG, "600": PYG, // Guarani
	"QAR": QAR, "qar": QAR, "634": QAR, // Qatari Rial
	"RON": RON, "ron": RON, "946": RON, // Leu
	"RSD": RSD, "rsd": RSD, "941": RSD, // Serbian Dinar
	"RUB": RUB, "rub": RUB, "643": RUB, // Russian Ruble
	"RWF": RWF, "rwf": RWF, "646": RWF, // Rwanda Franc
	"SAR": SAR, "sar": SAR, "682": SAR, // Saudi Riyal
	"SBD": SBD, "sbd": SBD, "090": SBD, // Solomon Islands Dollar
	"SCR": SCR, "scr": SCR, "690": SCR, // Seychelles Rupee
	"SDG": SDG, "sdg": SDG, "938": SDG, // Sudanese Pound
	"SEK": SEK, "sek": SEK, "752": SEK, // Swedish Krona
	"SGD": SGD, "sgd": SGD, "702": SGD, // Singapore Dollar
	"SHP": SHP, "shp": SHP, "654": SHP, // St. Helena Pound
	"SLL": SLL, "sll": SLL, "694": SLL, // Leone
	"SOS": SOS, "sos": SOS, "706": SOS, // Somali Shilling
	"SRD": SRD, "srd": SRD, "968": SRD, // Surinam Dollar
	"SSP": SSP, "ssp": SSP, "728": SSP, // South Sudanese Pound
	"STN": STN, "stn": STN, "930": STN, // Dobra
	"SYP": SYP, "syp": SYP, "760": SYP, // Syrian Pound
	"SZL": SZL, "szl": SZL, "748": SZL, // Lilangeni
	"THB": THB, "thb": THB, "764": THB, // Baht
	"TJS": TJS, "tjs": TJS, "972": TJS, // Somoni
	"TMT": TMT, "tmt": TMT, "934": TMT, // Manat
	"TND": TND, "tnd": TND, "788": TND, // Tunisian Dinar
	"TOP": TOP, "top": TOP, "776": TOP, // Pa'anga
	"TRY": TRY, "try": TRY, "949": TRY, // Turkish Lira
	"TTD": TTD, "ttd": TTD, "780": TTD, // Trinidad and Tobago Dollar
	"TWD": TWD, "twd": TWD, "901": TWD, // New Taiwan Dollar
	"TZS": TZS, "tzs": TZS, "834": TZS, // Tanzanian Shilling
	"UAH": UAH, "uah": UAH, "980": UAH, // Ukrainian Hryvnia
	"UGX": UGX, "ugx": UGX, "800": UGX, // Uganda Shilling
	"USD": USD, "usd": USD, "840": USD, // U.S. Dollar
	"UYU": UYU, "uyu": UYU, "858": UYU, // Peso Uruguayo
	"UZS": UZS, "uzs": UZS, "860": UZS, // Uzbekistan Sum
	"VES": VES, "ves": VES, "928": VES, // Sovereign Bolivar
	"VND": VND, "vnd": VND, "704": VND, // Dong
	"VUV": VUV, "vuv": VUV, "548": VUV, // Vatu
	"WST": WST, "wst": WST, "882": WST, // Tala
	"XAF": XAF, "xaf": XAF, "950": XAF, // CFA Franc BEAC
	"XCD": XCD, "xcd": XCD, "951": XCD, // East Caribbean Dollar
	"XOF": XOF, "xof": XOF, "952": XOF, // CFA Franc BCEAO
	"XPF": XPF, "xpf": XPF, "953": XPF, // CFP Franc
	"YER": YER, "yer": YER, "886": YER, // Yemeni Rial
	"ZAR": ZAR, "zar": ZAR, "710": ZAR, // Rand
	"ZMW": ZMW, "zmw": ZMW, "967": ZMW, // Zambian Kwacha
	"ZWL": ZWL, "zwl": ZWL, "932": ZWL, // Zimbabwe Dollar
}

var scaleLookup = [...]int8{
	XXX: 0, // No Currency
	XTS: 2, // Test Currency
	AED: 2, // U.A.E. Dirham
	AFN: 2, // Afghani
	ALL: 2, // Lek
	AMD: 2, // Armenian Dram
	ANG: 2, // Netherlands Antillian Guilder
	AOA: 2, // Kwanza
	ARS: 2, // Argentine Peso
	AUD: 2, // Australian Dollar
	AWG: 2, // Aruban Guilder
	AZN: 2, // Azerbaijan Manat
	BAM: 2, // Convertible Mark
	BBD: 2, // Barbados Dollar
	BDT: 2, // Taka
	BGN: 2, // Bulgarian Lev
	BHD: 3, // Bahraini Dinar
	BIF: 0, // Burundi Franc
	BMD: 2, // Bermudian Dollar
	BND: 2, // Brunei Dollar
	BOB: 2, // Boliviano
	BRL: 2, // Brazilian Real
	BSD: 2, // Bahamian Dollar
	BTN: 2, // Bhutan Ngultrum
	BWP: 2, // Pula
	BYN: 2, // Belarussian Ruble
	BZD: 2, // Belize Dollar
	CAD: 2, // Canadian Dollar
	CDF: 2, // Franc Congolais
	CHF: 2, // Swiss Franc
	CLP: 0, // Chilean Peso
	CNY: 2, // Yuan Renminbi
	COP: 2, // Colombian Peso
	CRC: 2, // Costa Rican Colon
	CUP: 2, // Cuban Peso
	CVE: 2, // Cape Verde Escudo
	CZK: 2, // Czech Koruna
	DJF: 0, // Djibouti Franc
	DKK: 2, // Danish Krone
	DOP: 2, // Dominican Peso
	DZD: 2, // Algerian Dinar
	EGP: 2, // Egyptian Pound
	ERN: 2, // Eritean Nakfa
	ETB: 2, // Ethiopian Birr
	EUR: 2, // Euro
	FJD: 2, // Fiji Dollar
	FKP: 2, // Falkland Islands Pound
	GBP: 2, // Pound Sterling
	GEL: 2, // Lari
	GHS: 2, // Cedi
	GIP: 2, // Gibraltar Pound
	GMD: 2, // Dalasi
	GNF: 0, // Guinea Franc
	GTQ: 2, // Quetzal
	GWP: 2, // Guinea-Bissau Peso
	GYD: 2, // Guyana Dollar
	HKD: 2, // Hong Kong Dollar
	HNL: 2, // Lempira
	HRK: 2, // Croatian Kuna
	HTG: 2, // Gourde
	HUF: 2, // Forint
	IDR: 2, // Rupiah
	ILS: 2, // Israeli Shequel
	INR: 2, // Indian Rupee
	IQD: 3, // Iraqi Dinar
	IRR: 2, // Iranian Rial
	ISK: 2, // Iceland Krona
	JMD: 2, // Jamaican Dollar
	JOD: 3, // Jordanian Dinar
	JPY: 0, // Yen
	KES: 2, // Kenyan Shilling
	KGS: 2, // Som
	KHR: 2, // Riel
	KMF: 0, // Comoro Franc
	KPW: 2, // North Korean Won
	KRW: 0, // Won
	KWD: 3, // Kuwaiti Dinar
	KYD: 2, // Cayman Islands Dollar
	KZT: 2, // Tenge
	LAK: 2, // Kip
	LBP: 2, // Lebanese Pound
	LKR: 2, // Sri Lanka Rupee
	LRD: 2, // Liberian Dollar
	LSL: 2, // Lesotho Loti
	LYD: 3, // Libyan Dinar
	MAD: 2, // Moroccan Dirham
	MDL: 2, // Moldovan Leu
	MGA: 2, // Malagasy Ariary
	MKD: 2, // Denar
	MMK: 2, // Kyat
	MNT: 2, // Tugrik
	MOP: 2, // Pataca
	MRU: 2, // Ouguiya
	MUR: 2, // Mauritius Rupee
	MVR: 2, // Rufiyaa
	MWK: 2, // Malawi Kwacha
	MXN: 2, // Mexican Peso
	MYR: 2, // Malaysian Ringgit
	MZN: 2, // Mozambique Metical
	NAD: 2, // Namibia Dollar
	NGN: 2, // Naira
	NIO: 2, // Cordoba Oro
	NOK: 2, // Norwegian Krone
	NPR: 2, // Nepalese Rupee
	NZD: 2, // New Zealand Dollar
	OMR: 3, // Rial Omani
	PAB: 2, // Balboa
	PEN: 2, // Sol
	PGK: 2, // Kina
	PHP: 2, // Philippine Peso
	PKR: 2, // Pakistan Rupee
	PLN: 2, // Zloty
	PYG: 0, // Guarani
	QAR: 2, // Qatari Rial
	RON: 2, // Leu
	RSD: 2, // Serbian Dinar
	RUB: 2, // Russian Ruble
	RWF: 0, // Rwanda Franc
	SAR: 2, // Saudi Riyal
	SBD: 2, // Solomon Islands Dollar
	SCR: 2, // Seychelles Rupee
	SDG: 2, // Sudanese Pound
	SEK: 2, // Swedish Krona
	SGD: 2, // Singapore Dollar
	SHP: 2, // St. Helena Pound
	SLL: 2, // Leone
	SOS: 2, // Somali Shilling
	SRD: 2, // Surinam Dollar
	SSP: 2, // South Sudanese Pound
	STN: 2, // Dobra
	SYP: 2, // Syrian Pound
	SZL: 2, // Lilangeni
	THB: 2, // Baht
	TJS: 2, // Somoni
	TMT: 2, // Manat
	TND: 3, // Tunisian Dinar
	TOP: 2, // Pa'anga
	TRY: 2, // Turkish Lira
	TTD: 2, // Trinidad and Tobago Dollar
	TWD: 2, // New Taiwan Dollar
	TZS: 2, // Tanzanian Shilling
	UAH: 2, // Ukrainian Hryvnia
	UGX: 0, // Uganda Shilling
	USD: 2, // U.S. Dollar
	UYU: 2, // Peso Uruguayo
	UZS: 2, // Uzbekistan Sum
	VES: 2, // Sovereign Bolivar
	VND: 0, // Dong
	VUV: 0, // Vatu
	WST: 2, // Tala
	XAF: 0, // CFA Franc BEAC
	XCD: 2, // East Caribbean Dollar
	XOF: 0, // CFA Franc BCEAO
	XPF: 0, // CFP Franc
	YER: 2, // Yemeni Rial
	ZAR: 2, // Rand
	ZMW: 2, // Zambian Kwacha
	ZWL: 2, // Zimbabwe Dollar
}

var numLookup = [...]string{
	XXX: "999", // No Currency
	XTS: "963", // Test Currency
	AED: "784", // U.A.E. Dirham
	AFN: "971", // Afghani
	ALL: "008", // Lek
	AMD: "051", // Armenian Dram
	ANG: "532", // Netherlands Antillian Guilder
	AOA: "973", // Kwanza
	ARS: "032", // Argentine Peso
	AUD: "036", // Australian Dollar
	AWG: "533", // Aruban Guilder
	AZN: "944", // Azerbaijan Manat
	BAM: "977", // Convertible Mark
	BBD: "052", // Barbados Dollar
	BDT: "050", // Taka
	BGN: "975", // Bulgarian Lev
	BHD: "048", // Bahraini Dinar
	BIF: "108", // Burundi Franc
	BMD: "060", // Bermudian Dollar
	BND: "096", // Brunei Dollar
	BOB: "068", // Boliviano
	BRL: "986", // Brazilian Real
	BSD: "044", // Bahamian Dollar
	BTN: "064", // Bhutan Ngultrum
	BWP: "072", // Pula
	BYN: "933", // Belarussian Ruble
	BZD: "084", // Belize Dollar
	CAD: "124", // Canadian Dollar
	CDF: "976", // Franc Congolais
	CHF: "756", // Swiss Franc
	CLP: "152", // Chilean Peso
	CNY: "156", // Yuan Renminbi
	COP: "170", // Colombian Peso
	CRC: "188", // Costa Rican Colon
	CUP: "192", // Cuban Peso
	CVE: "132", // Cape Verde Escudo
	CZK: "203", // Czech Koruna
	DJF: "262", // Djibouti Franc
	DKK: "208", // Danish Krone
	DOP: "214", // Dominican Peso
	DZD: "012", // Algerian Dinar
	EGP: "818", // Egyptian Pound
	ERN: "232", // Eritean Nakfa
	ETB: "230", // Ethiopian Birr
	EUR: "978", // Euro
	FJD: "242", // Fiji Dollar
	FKP: "238", // Falkland Islands Pound
	GBP: "826", // Pound Sterling
	GEL: "981", // Lari
	GHS: "936", // Cedi
	GIP: "292", // Gibraltar Pound
	GMD: "270", // Dalasi
	GNF: "324", // Guinea Franc
	GTQ: "320", // Quetzal
	GWP: "624", // Guinea-Bissau Peso
	GYD: "328", // Guyana Dollar
	HKD: "344", // Hong Kong Dollar
	HNL: "340", // Lempira
	HRK: "191", // Croatian Kuna
	HTG: "332", // Gourde
	HUF: "348", // Forint
	IDR: "360", // Rupiah
	ILS: "376", // Israeli Shequel
	INR: "356", // Indian Rupee
	IQD: "368", // Iraqi Dinar
	IRR: "364", // Iranian Rial
	ISK: "352", // Iceland Krona
	JMD: "388", // Jamaican Dollar
	JOD: "400", // Jordanian Dinar
	JPY: "392", // Yen
	KES: "404", // Kenyan Shilling
	KGS: "417", // Som
	KHR: "116", // Riel
	KMF: "174", // Comoro Franc
	KPW: "408", // North Korean Won
	KRW: "410", // Won
	KWD: "414", // Kuwaiti Dinar
	KYD: "136", // Cayman Islands Dollar
	KZT: "398", // Tenge
	LAK: "418", // Kip
	LBP: "422", // Lebanese Pound
	LKR: "144", // Sri Lanka Rupee
	LRD: "430", // Liberian Dollar
	LSL: "426", // Lesotho Loti
	LYD: "434", // Libyan Dinar
	MAD: "504", // Moroccan Dirham
	MDL: "498", // Moldovan Leu
	MGA: "969", // Malagasy Ariary
	MKD: "807", // Denar
	MMK: "104", // Kyat
	MNT: "496", // Tugrik
	MOP: "446", // Pataca
	MRU: "929", // Ouguiya
	MUR: "480", // Mauritius Rupee
	MVR: "462", // Rufiyaa
	MWK: "454", // Malawi Kwacha
	MXN: "484", // Mexican Peso
	MYR: "458", // Malaysian Ringgit
	MZN: "943", // Mozambique Metical
	NAD: "516", // Namibia Dollar
	NGN: "566", // Naira
	NIO: "558", // Cordoba Oro
	NOK: "578", // Norwegian Krone
	NPR: "524", // Nepalese Rupee
	NZD: "554", // New Zealand Dollar
	OMR: "512", // Rial Omani
	PAB: "590", // Balboa
	PEN: "604", // Sol
	PGK: "598", // Kina
	PHP: "608", // Philippine Peso
	PKR: "586", // Pakistan Rupee
	PLN: "985", // Zloty
	PYG: "600", // Guarani
	QAR: "634", // Qatari Rial
	RON: "946", // Leu
	RSD: "941", // Serbian Dinar
	RUB: "643", // Russian Ruble
	RWF: "646", // Rwanda Franc
	SAR: "682", // Saudi Riyal
	SBD: "090", // Solomon Islands Dollar
	SCR: "690", // Seychelles Rupee
	SDG: "938", // Sudanese Pound
	SEK: "752", // Swedish Krona
	SGD: "702", // Singapore Dollar
	SHP: "654", // St. Helena Pound
	SLL: "694", // Leone
	SOS: "706", // Somali Shilling
	SRD: "968", // Surinam Dollar
	SSP: "728", // South Sudanese Pound
	STN: "930", // Dobra
	SYP: "760", // Syrian Pound
	SZL: "748", // Lilangeni
	THB: "764", // Baht
	TJS: "972", // Somoni
	TMT: "934", // Manat
	TND: "788", // Tunisian Dinar
	TOP: "776", // Pa'anga
	TRY: "949", // Turkish Lira
	TTD: "780", // Trinidad and Tobago Dollar
	TWD: "901", // New Taiwan Dollar
	TZS: "834", // Tanzanian Shilling
	UAH: "980", // Ukrainian Hryvnia
	UGX: "800", // Uganda Shilling
	USD: "840", // U.S. Dollar
	UYU: "858", // Peso Uruguayo
	UZS: "860", // Uzbekistan Sum
	VES: "928", // Sovereign Bolivar
	VND: "704", // Dong
	VUV: "548", // Vatu
	WST: "882", // Tala
	XAF: "950", // CFA Franc BEAC
	XCD: "951", // East Caribbean Dollar
	XOF: "952", // CFA Franc BCEAO
	XPF: "953", // CFP Franc
	YER: "886", // Yemeni Rial
	ZAR: "710", // Rand
	ZMW: "967", // Zambian Kwacha
	ZWL: "932", // Zimbabwe Dollar
}

var codeLookup = [...]string{
	XXX: "XXX", // No Currency
	XTS: "XTS", // Test Currency
	AED: "AED", // U.A.E. Dirham
	AFN: "AFN", // Afghani
	ALL: "ALL", // Lek
	AMD: "AMD", // Armenian Dram
	ANG: "ANG", // Netherlands Antillian Guilder
	AOA: "AOA", // Kwanza
	ARS: "ARS", // Argentine Peso
	AUD: "AUD", // Australian Dollar
	AWG: "AWG", // Aruban Guilder
	AZN: "AZN", // Azerbaijan Manat
	BAM: "BAM", // Convertible Mark
	BBD: "BBD", // Barbados Dollar
	BDT: "BDT", // Taka
	BGN: "BGN", // Bulgarian Lev
	BHD: "BHD", // Bahraini Dinar
	BIF: "BIF", // Burundi Franc
	BMD: "BMD", // Bermudian Dollar
	BND: "BND", // Brunei Dollar
	BOB: "BOB", // Boliviano
	BRL: "BRL", // Brazilian Real
	BSD: "BSD", // Bahamian Dollar
	BTN: "BTN", // Bhutan Ngultrum
	BWP: "BWP", // Pula
	BYN: "BYN", // Belarussian Ruble
	BZD: "BZD", // Belize Dollar
	CAD: "CAD", // Canadian Dollar
	CDF: "CDF", // Franc Congolais
	CHF: "CHF", // Swiss Franc
	CLP: "CLP", // Chilean Peso
	CNY: "CNY", // Yuan Renminbi
	COP: "COP", // Colombian Peso
	CRC: "CRC", // Costa Rican Colon
	CUP: "CUP", // Cuban Peso
	CVE: "CVE", // Cape Verde Escudo
	CZK: "CZK", // Czech Koruna
	DJF: "DJF", // Djibouti Franc
	DKK: "DKK", // Danish Krone
	DOP: "DOP", // Dominican Peso
	DZD: "DZD", // Algerian Dinar
	EGP: "EGP", // Egyptian Pound
	ERN: "ERN", // Eritean Nakfa
	ETB: "ETB", // Ethiopian Birr
	EUR: "EUR", // Euro
	FJD: "FJD", // Fiji Dollar
	FKP: "FKP", // Falkland Islands Pound
	GBP: "GBP", // Pound Sterling
	GEL: "GEL", // Lari
	GHS: "GHS", // Cedi
	GIP: "GIP", // Gibraltar Pound
	GMD: "GMD", // Dalasi
	GNF: "GNF", // Guinea Franc
	GTQ: "GTQ", // Quetzal
	GWP: "GWP", // Guinea-Bissau Peso
	GYD: "GYD", // Guyana Dollar
	HKD: "HKD", // Hong Kong Dollar
	HNL: "HNL", // Lempira
	HRK: "HRK", // Croatian Kuna
	HTG: "HTG", // Gourde
	HUF: "HUF", // Forint
	IDR: "IDR", // Rupiah
	ILS: "ILS", // Israeli Shequel
	INR: "INR", // Indian Rupee
	IQD: "IQD", // Iraqi Dinar
	IRR: "IRR", // Iranian Rial
	ISK: "ISK", // Iceland Krona
	JMD: "JMD", // Jamaican Dollar
	JOD: "JOD", // Jordanian Dinar
	JPY: "JPY", // Yen
	KES: "KES", // Kenyan Shilling
	KGS: "KGS", // Som
	KHR: "KHR", // Riel
	KMF: "KMF", // Comoro Franc
	KPW: "KPW", // North Korean Won
	KRW: "KRW", // Won
	KWD: "KWD", // Kuwaiti Dinar
	KYD: "KYD", // Cayman Islands Dollar
	KZT: "KZT", // Tenge
	LAK: "LAK", // Kip
	LBP: "LBP", // Lebanese Pound
	LKR: "LKR", // Sri Lanka Rupee
	LRD: "LRD", // Liberian Dollar
	LSL: "LSL", // Lesotho Loti
	LYD: "LYD", // Libyan Dinar
	MAD: "MAD", // Moroccan Dirham
	MDL: "MDL", // Moldovan Leu
	MGA: "MGA", // Malagasy Ariary
	MKD: "MKD", // Denar
	MMK: "MMK", // Kyat
	MNT: "MNT", // Tugrik
	MOP: "MOP", // Pataca
	MRU: "MRU", // Ouguiya
	MUR: "MUR", // Mauritius Rupee
	MVR: "MVR", // Rufiyaa
	MWK: "MWK", // Malawi Kwacha
	MXN: "MXN", // Mexican Peso
	MYR: "MYR", // Malaysian Ringgit
	MZN: "MZN", // Mozambique Metical
	NAD: "NAD", // Namibia Dollar
	NGN: "NGN", // Naira
	NIO: "NIO", // Cordoba Oro
	NOK: "NOK", // Norwegian Krone
	NPR: "NPR", // Nepalese Rupee
	NZD: "NZD", // New Zealand Dollar
	OMR: "OMR", // Rial Omani
	PAB: "PAB", // Balboa
	PEN: "PEN", // Sol
	PGK: "PGK", // Kina
	PHP: "PHP", // Philippine Peso
	PKR: "PKR", // Pakistan Rupee
	PLN: "PLN", // Zloty
	PYG: "PYG", // Guarani
	QAR: "QAR", // Qatari Rial
	RON: "RON", // Leu
	RSD: "RSD", // Serbian Dinar
	RUB: "RUB", // Russian Ruble
	RWF: "RWF", // Rwanda Franc
	SAR: "SAR", // Saudi Riyal
	SBD: "SBD", // Solomon Islands Dollar
	SCR: "SCR", // Seychelles Rupee
	SDG: "SDG", // Sudanese Pound
	SEK: "SEK", // Swedish Krona
	SGD: "SGD", // Singapore Dollar
	SHP: "SHP", // St. Helena Pound
	SLL: "SLL", // Leone
	SOS: "SOS", // Somali Shilling
	SRD: "SRD", // Surinam Dollar
	SSP: "SSP", // South Sudanese Pound
	STN: "STN", // Dobra
	SYP: "SYP", // Syrian Pound
	SZL: "SZL", // Lilangeni
	THB: "THB", // Baht
	TJS: "TJS", // Somoni
	TMT: "TMT", // Manat
	TND: "TND", // Tunisian Dinar
	TOP: "TOP", // Pa'anga
	TRY: "TRY", // Turkish Lira
	TTD: "TTD", // Trinidad and Tobago Dollar
	TWD: "TWD", // New Taiwan Dollar
	TZS: "TZS", // Tanzanian Shilling
	UAH: "UAH", // Ukrainian Hryvnia
	UGX: "UGX", // Uganda Shilling
	USD: "USD", // U.S. Dollar
	UYU: "UYU", // Peso Uruguayo
	UZS: "UZS", // Uzbekistan Sum
	VES: "VES", // Sovereign Bolivar
	VND: "VND", // Dong
	VUV: "VUV", // Vatu
	WST: "WST", // Tala
	XAF: "XAF", // CFA Franc BEAC
	XCD: "XCD", // East Caribbean Dollar
	XOF: "XOF", // CFA Franc BCEAO
	XPF: "XPF", // CFP Franc
	YER: "YER", // Yemeni Rial
	ZAR: "ZAR", // Rand
	ZMW: "ZMW", // Zambian Kwacha
	ZWL: "ZWL", // Zimbabwe Dollar
}
